[versions]
agp = "8.0.0"
kotlin = "1.8.20"
appcompat = "1.6.1"
material = "1.9.0"
junit = "4.13.2"
espresso_core = "3.5.1"
ext_junit = "1.1.5"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }


androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
extJunit = { module = "androidx.test.ext:junit", version = "ext.junit" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso.core" }

[plugins]